using System.Numerics;

namespace Biasfish.Core
{
    public static class Knights
    {
        public static readonly ulong[] KnightAttacks = new ulong[64];

        static Knights()
        {
            // NOTE: this method was generated by Gemini
            for (int square = 0; square < 64; square++)
            {
                ulong knight = 1UL << square;
                ulong attacks = 0;

                // Shift the knight to its 8 possible targets.
                // We use bitwise AND with masks to prevent the knight from wrapping 
                // around the edges of the board (e.g. jumping from A-file to H-file).
                attacks |= (knight << 17) & 0xFEFEFEFEFEFEFEFE; // Up 2, Right 1
                attacks |= (knight << 15) & 0x7F7F7F7F7F7F7F7F; // Up 2, Left 1
                attacks |= (knight << 10) & 0xFCFCFCFCFCFCFCFC; // Up 1, Right 2
                attacks |= (knight <<  6) & 0x3F3F3F3F3F3F3F3F; // Up 1, Left 2
                attacks |= (knight >> 15) & 0xFEFEFEFEFEFEFEFE; // Down 2, Right 1
                attacks |= (knight >> 17) & 0x7F7F7F7F7F7F7F7F; // Down 2, Left 1
                attacks |= (knight >>  6) & 0xFCFCFCFCFCFCFCFC; // Down 1, Right 2
                attacks |= (knight >> 10) & 0x3F3F3F3F3F3F3F3F; // Down 1, Left 2

                KnightAttacks[square] = attacks;
            }
        }

        public static MoveList GetPseudoLegal(ref Board board, ref MoveList moveList)
        {
            ulong friendly = board.GetBitboard(board.sideToMove);
            ulong knights = board.GetBitboard(Piece.Knights | board.sideToMove);

            while (knights != 0)
            {
                int fromSquare = BitOperations.TrailingZeroCount(knights);
                ulong knightAttacks = KnightAttacks[fromSquare] & ~friendly; // mask friendly pieces

                while (knightAttacks != 0)
                {
                    int toSquare = BitOperations.TrailingZeroCount(knightAttacks);
                    moveList.Add(new Move(fromSquare, toSquare, 0));

                    knightAttacks &= knightAttacks - 1; // this clears the lsb
                }
                knights &= knights - 1; // this clears the lsb
            }

            return moveList;
        }
    }
}